/* SizeMyPDF service worker - generated by build.js, do not edit. */
const CACHE = 'sizemypdf-937be39a5f';
const PRECACHE = [
  "./",
  "./tools.html",
  "./css/style.css",
  "./js/app.js",
  "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js",
  "https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js",
  "https://cdnjs.cloudflare.com/ajax/libs/pdf-lib/1.17.1/pdf-lib.min.js"
];

self.addEventListener('install', e => {
  // Individually, so one failed CDN fetch cannot abort the whole install.
  e.waitUntil(caches.open(CACHE).then(c =>
    Promise.all(PRECACHE.map(u => c.add(u).catch(() => null)))
  ).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Never touch advertising, analytics or consent traffic - caching it would
  // both break it and misrepresent what the visitor actually loaded.
  if (/googlesyndication|doubleclick|adtrafficquality|googletagservices|cloudflareinsights/
      .test(url.hostname)) return;

  const sameOrigin = url.origin === self.location.origin;
  const isLib = url.hostname === 'cdnjs.cloudflare.com';
  if (!sameOrigin && !isLib) return;

  // Libraries are version-pinned in their path, so cache-first is safe and is
  // what makes offline work. Pages go network-first so content stays fresh.
  if (isLib) {
    e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(res => {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
      return res;
    })));
    return;
  }

  e.respondWith(fetch(req).then(res => {
    const copy = res.clone();
    caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
    return res;
  }).catch(() => caches.match(req).then(hit => hit ||
    (req.mode === 'navigate' ? caches.match('./') : undefined))));
});
