/* SizeMyPDF service worker - generated by build.js, do not edit. */
const CACHE = 'sizemypdf-9a6056f4e3';
const PRECACHE = [
  "./",
  "./tools.html",
  "./offline.html",
  "./css/style.css?v=abd394c7",
  "./js/pdfjs-raf.js?v=2e128684",
  "./js/metrics.js?v=a83c46f8",
  "./js/compress-core.js?v=b1ddd715",
  "./js/app.js?v=c24270d5",
  "./js/compress-worker.js?v=a5a4ac09"
];

self.addEventListener('install', e => {
  // Individually, so one failed fetch cannot abort the whole install.
  e.waitUntil(caches.open(CACHE).then(c =>
    Promise.all(PRECACHE.map(u => c.add(u).catch(() => null)))
  ).then(() => self.skipWaiting()));
});

self.addEventListener('activate', e => {
  e.waitUntil(caches.keys()
    .then(ks => Promise.all(ks.filter(k => k !== CACHE).map(k => caches.delete(k))))
    .then(() => self.clients.claim()));
});

self.addEventListener('fetch', e => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);

  // Never touch advertising, analytics or consent traffic - caching it would
  // both break it and misrepresent what the visitor actually loaded.
  if (/googlesyndication|doubleclick|adtrafficquality|googletagservices|cloudflareinsights/
      .test(url.hostname)) return;

  if (url.origin !== self.location.origin) return;
  const isLib = url.pathname.indexOf('/vendor/') !== -1;

  // vendor/ holds version-pinned library builds that only change when the file
  // itself is replaced, so cache-first is safe and is what makes offline work.
  // Pages go network-first so content stays fresh.
  // Only ever store a response that actually succeeded. Without this a 404 or
  // a 500 served during a deploy is cached and then handed back offline
  // indefinitely, so the visitor sees a broken page for a file that is fine.
  function keep(res) {
    if (res && res.ok) {
      const copy = res.clone();
      caches.open(CACHE).then(c => c.put(req, copy)).catch(() => {});
    }
    return res;
  }

  if (isLib) {
    e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(keep)));
    return;
  }

  e.respondWith(fetch(req).then(keep).catch(() => caches.match(req).then(hit => {
    if (hit) return hit;
    // Falling back to the homepage would silently hand someone the compressor
    // when they asked for Merge, and they would assume they misclicked. Say
    // what happened instead.
    if (req.mode === 'navigate') return caches.match('./offline.html');
    return undefined;
  })));
});
